version: "3.7"
services:
  calculator-server:
    image: aruns1975/calculator-server
    ports:
      - 8080:8080
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == worker
  
  calculator-client:
    image: aruns1975/calculator-client
    ports:
      - 80:9090
    environment:
      - calculator.server.url=calculator-server
      - calculator.server.port=8080
    deploy:
      replicas: 1